ESC Setup / programming (bidirectional telemetry / forward programming) - implemented for HW5 ESCs
rotorflight/rotorflight-firmware pull request #114
Opened 2024-05-14 15:26 UTC by bob01

ESC setup / programming (forward programming) using the Tx via bidirectional telemetry #101

Complete for HobbyWing V5

- Implemented on common request / response finite state machine (rrfsm), uses common ESC parameter read and write pattern and common MSP transport as #108 

### Configuration
- same as #108 

### Code
- TELEMETRY_BUFFER_SIZE increased to accommodate larger HW5 responses
- rrfsm protocol callback signature changed to accept time in Us vs Ms for protocols like HW5 which need to see the higher resolution timer
- out of band metadata value sent every 128 tele frame as ESC status value  that Tx widgets can use to...
   - identify ESC (for supported ESCs)
   - signal that ESC needs to be reset (for new settings to take effect / unsolicited telemetry to resume)
   - or can be ignored.

#### HW5 support
- configure FC as 'HobbyWing v5'
- requires Platinum 5 ESC, tested with PL-04.0.11 and current version PL-04.1.02
- ESC can be configured at any time, restart required - ESC must be power-cycled e.g.
   - bench setup or adjustments in the pits
 
![image](https://github.com/bob01/etx-tools/assets/4014433/b727b4ce-75dc-4cf8-9965-19aec3bf1f70)
![image](https://github.com/bob01/etx-tools/assets/4014433/997232a0-6fa8-49f1-ae17-a096016cc8a4)
![image](https://github.com/bob01/etx-tools/assets/4014433/12a27925-0e76-45e5-a296-bf3177b1f8f9)
![image](https://github.com/bob01/etx-tools/assets/4014433/1f886098-0e5d-4a47-a58c-40b9f96eaedf)
![image](https://github.com/bob01/etx-tools/assets/4014433/b3125f87-88ae-4756-8abc-4c420a0afcaa)
![image](https://github.com/bob01/etx-tools/assets/4014433/2980b767-cd56-4446-aa22-60eaecb3a32a)
![image](https://github.com/bob01/etx-tools/assets/4014433/028ebd5c-f606-4496-a58a-db9d6775f8a1)
![image](https://github.com/rotorflight/rotorflight-firmware/assets/4014433/dfdad2eb-4f54-42bb-a740-29a701c0e93f)

2024-05-16 10:20 UTC, rotorflight requested changes
Minor tweaks needed

2024-05-16 10:20 UTC, rotorflight commented on src/main/sensors/esc_sensor.c
> +static bool tribCrankUncSetup(timeMs_t currentTimeUs)
Should be `timeUs_t`

2024-05-16 10:20 UTC, rotorflight commented on src/main/sensors/esc_sensor.c
> +typedef bool (*rrfsmStartCallbackPtr)(timeMs_t currentTimeUs);  // return true to continue w/ default initialization (if in doubt return true)
Should be `timeUs_t`

2024-05-16 10:20 UTC, rotorflight commented on src/main/sensors/esc_sensor.c
> +typedef bool (*rrfsmCrankCallbackPtr)(timeMs_t currentTimeUs);  // return true to continue w/ default loop (advanced, if in doubt return true)
`timeUs_t`

2024-05-16 10:20 UTC, rotorflight commented on src/main/sensors/esc_sensor.c
> +{
`(void)`

2024-05-16 13:27 UTC, bob01 commented on src/main/sensors/esc_sensor.c
> +{
timeUs_t and fn(void) usage addressed

2024-05-17 08:16 UTC, rotorflight approved these changes

2024-05-17 08:17 UTC, merged