Correctde CMS copy profiles, was hardcoded for 3 profiles only.
rotorflight/rotorflight-firmware pull request #121
Opened 2024-06-16 09:58 UTC by AndersHoglund

CMS copy profiles was hard coded for 3 profiles only. Now follows config item PROFILE_COUNT, up to max 6 profiles.

2024-06-27 14:19 UTC, rotorflight requested changes

2024-06-27 14:19 UTC, rotorflight commented on src/main/cms/cms_menu_imu.c
> +    ,"4"
I suggest using "...", (comma in the end for all entries)
as it is more readable. C allows the comma after the last entry, so that's not a problem.

2024-06-27 14:19 UTC, rotorflight commented on src/main/cms/cms_menu_imu.c
> +    ,"4"
No need to figure out the max number of profiles... you could simply define the names for 6, as thats the maximum

2024-06-28 08:50 UTC, AndersHoglund commented
OK, updated according to comment.

2024-06-28 22:16 UTC, rotorflight approved these changes

2024-06-28 22:17 UTC, merged