Nicer log file name and FAT long file name support
rotorflight/rotorflight-firmware pull request #212
Opened 2024-12-27 19:42 UTC by gongtao0607

This PR changes the naming schema of the log files and adds FAT LFN support to emfat.

![Screenshot 2024-12-27 110205](https://github.com/user-attachments/assets/cd76eb4f-86b4-4140-a892-8d716049e071)
![Screenshot 2024-12-27 110301](https://github.com/user-attachments/assets/e35fec6d-d6cf-4ae6-a26d-1a79db0f9699)

2024-12-28 12:52 UTC, rotorflight requested changes
Please strip trailing whitespace on all new lines.
Even better, configure your editor to do it for you!

2024-12-28 12:53 UTC, rotorflight commented
In fact, I should add a check in the PR-CI that would automatically notify the author if there are traling whitespaces or other formatting issues... TBD.

2024-12-28 13:20 UTC, rotorflight commented
I wonder... While we are at it, maybe we can use the craft name instead of RTFL_ prefix.
With spaces and other special characters replaced with _ or something.

2024-12-29 01:39 UTC, gongtao0607 commented
> Please strip trailing whitespace on all new lines. Even better, configure your editor to do it for you!

Done both. https://github.com/rotorflight/rotorflight-firmware/pull/212/commits/0a189fa910df6a3276b6cbe30a9114b2b5dff35d


> I wonder... While we are at it, maybe we can use the craft name instead of RTFL_ prefix. With spaces and other special characters replaced with _ or something.

Sounds useful. https://github.com/rotorflight/rotorflight-firmware/pull/212/commits/207eeafdee3d8c25a3f79efdb8bf432ccc82bfd5

![Screenshot 2024-12-28 173835](https://github.com/user-attachments/assets/1eec5955-c6c8-48ad-ac10-6a2d9bb17e65)


Please take another look

2024-12-29 13:29 UTC, rotorflight commented
Sorry to be PITA. What the craft name is empty? Now it would have two underscores.

2024-12-30 01:17 UTC, gongtao0607 commented
> Sorry to be PITA. What the craft name is empty? Now it would have two underscores.

I thought about it and I thought it's fine as any illegal chars all turn to extra underscores. 
Anyway here's the change: https://github.com/rotorflight/rotorflight-firmware/pull/212/commits/f15244fff9aef9e4cf38ce9260ee3adee01d3fb7

2025-01-01 12:20 UTC, rotorflight approved these changes

2025-01-01 12:23 UTC, merged