Fix for current FW Kontronik ESCs - verified Kolibri v3.0/v3.5, Kosmik 200 HV v4.17
rotorflight/rotorflight-firmware pull request #98
Opened 2024-04-14 03:49 UTC by bob01

Current ESC FW for the Jive (v1.17) / Kolibri (3.0 - 3.5) / Kosmik (v4.17) are 40 byte data + 44 byte info.
JivePro/Kosmic v*.13 were different 38 byte w/ 32 byte payload, 2 extra bytes and 4 byte CRC, based on release notes it is likely that the *.14 versions switched to the current 40 byte packet but this could not be verified due to lack of test subjects.

This is a simple fix to support modern 40 byte packet - a more elaborate scheme to support older controllers is outside of RF RC scope, possible future consideration.

Kosmik 250 HV-I could not be properly verified due to what appears to be an unrelated defect - versions 1.17 - 1.25 appeared to produce correct 40 byte but broken frames.

2024-04-14 08:12 UTC, rotorflight requested changes
Can you also fix the protocol listing above. I think it doesn't list the two reserved bytes.

2024-04-14 10:06 UTC, bob01 commented
Sure - this was also accidentally checked into master - fixing that - will likely resubmit PR

2024-04-14 22:36 UTC, bob01 commented
Suggest reviewing https://github.com/rotorflight/rotorflight-firmware/pull/99 instead.

2024-04-15 08:39 UTC, rotorflight approved these changes

2024-04-15 08:42 UTC, merged